config/routes.rb
Rails.application.routes.draw do

  root 'player#index'

  post '/' => 'player#create'

  get 'statistic/data', :defaults => { :format => 'json' }

  get 'graphic/data', :defaults => { :format => 'json' }

  get 'fixture/data', :defaults => { :format => 'json' }

  resources :player, controller: :player

  resources :fixture, controller: :fixture

  resources :statistic, controller: :statistic

  resources :graphic, controller: :graphic
  

end

app/models/fixture.rb
class Fixture < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index

  end
end

app/controllers/fixture_controller.rb
class FixtureController < ApplicationController

  def index
    http = HTTPClient.new
    team_data = http.get_content('http://api.football-data.org/alpha/teams/57/fixtures', nil, {'X-Auth-Token' => '663528934d21408f8a4a638a6511cdb5'})
    @team_data = JSON.parse(team_data)
    p @team_data
    @team_data['fixtures'].each do |f|
      fixture = Fixture.find_or_create_by(date: f['date'])

      fixture.update(away_team: f['awayTeamName'])
      fixture.update(home_team: f['homeTeamName'])
      fixture.update(away_team_goals: f['result']['goalsAwayTeam'])
      fixture.update(home_team_goals: f['result']['goalsHomeTeam'])

      if (f['homeTeamName'] != 'Arsenal FC')
        fixture.update(opponent: f['homeTeamName'])
      else 
        fixture.update(opponent: f['awayTeamName'])
      end
    end

    @fixtures = @team_data['fixtures']
  end 

  def data
    fixture_data = Fixture.all
    respond_to do |format|
      format.json {
        render :json => fixture_data
      }
    end
  end

end

app/controllers/graphic_controller.rb
class GraphicController < ApplicationController

  def index
  end

  def data
    players_data = Player.all
    respond_to do |format|
      format.json {
        render :json => players_data
      }
    end
  end

end

app/controllers/player_controller.rb
require 'flickraw'

FlickRaw.api_key='f4b1ce80af46485e18c007222f6f725b'
FlickRaw.shared_secret='c4461182866476c2'

class PlayerController < ApplicationController

  def index
    @players = Player.all

    http = HTTPClient.new

    team_data = http.get_content('http://api.football-data.org/alpha/teams/57', nil, {'X-Auth-Token' => '663528934d21408f8a4a638a6511cdb5'})
    @team_data = JSON.parse(team_data)
    @market = @team_data['squadMarketValue']

    player_data = http.get_content('http://api.football-data.org/alpha/teams/57/players', nil, {'X-Auth-Token' => '663528934d21408f8a4a638a6511cdb5'} )
    @player_data = JSON.parse(player_data)
    @player_data = @player_data['players']

    @players.each do |player| 
      @player_data.each do |p|
        if (player.name == p['name'] && !player['marketValue'])
         player['marketValue'] = p['marketValue']
        end
      end   
    end
  end

  def create
    @player = Player.create(player_params)
    redirect_to player_index_path
  end

  def show
    p params[:id]
    @player = Player.find(params[:id])

    list = flickr.photos.search :text => @player.name, :sort => "relevance"
    photos = list.map do |i|
       "https:/farm3.static.flickr.com/#{i["server"]}/" "#{i["id"]}_" "#{i["secret"]}_n.jpg"
    end
    @photo = photos.sample
  end


  def edit
    @player = Player.find(params[:id])
    render layout: false
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    redirect_to player_index_path
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to player_index_path
  end


  private

  def player_params
    params.require(:player).permit(:name, :age, :nationality, :position)
  end


end

app/controllers/statistic_controller.rb
class StatisticController < ApplicationController


  def psql_data data, num=2
    psql_array = []

    if (num < 2 || !(data.kind_of?(Array)) )
      raise 'Invalid input' 
    end

    data[1..num].each do |d|
      psql_array << Hash[data[0].zip(d)]
    end

    return psql_array
  end



  def index
    http = HTTPClient.new

    statistics = http.get_content('http://jokecamp.github.io/epl-fantasy-geek/js/static-data.json')
    @statistics = JSON.parse(statistics)
    @data = @statistics['elements']

    Player.all.each do |p|
      @data.each do |d|
        temp = d['second_name']
        if (p.name.split(' ')[1] == temp)
          name = p.name
          player = Player.find_by name: name
          player.update(goals: d['goals_scored'])
          player.update(assists: d['assists'])
          player.update(minutes: d['minutes'])
          player.update(clean_sheets: d['clean_sheets'])
          player.update(saves: d['saves'])
          player.update(goals_conceded: d['goals_conceded'])
        end
      end
    end

    @players = Player.all
  end
  

  def data
    players_data = Player.all
    respond_to do |format|
      format.json {
        render :json => players_data
      }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/fixture/index.html.erb
<h1>2015-16 Results</h1>

 <table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Home Team</th>
      <th></th>
      <th></th>
      <th>Away Team</th>
      <th></th>
    </tr>
  </thead>
<% @fixtures.each do |f| %>
  <tr>
    <td> <%= Time.parse(f['date']).strftime("%B %e, %Y, %H:%M") %></td>
    <td> <%= f['homeTeamName'] %></td>
    <td> <%= f['result']['goalsHomeTeam'] == -1 ? '-' : f['result']['goalsHomeTeam'] %></td>
    <td></td>
    <td> <%= f['awayTeamName'] %></td>
    <td> <%= f['result']['goalsAwayTeam'] == -1 ? '-' : f['result']['goalsAwayTeam'] %></td>
  </tr>
  <% end %>
</table>

app/views/graphic/index.html.erb
<div id="canvas"></div>
<svg id="linechart"></svg>
<svg id="scatterplot"></svg>


<div class="stat-modal">
  <div class="close-modal">X</div>
  <table class="modal-table table">
    <tr> 
      <th><strong>Player Name</strong></th>
      <th><strong>Goals</strong></th>
    </tr>
    <tr>
      <td class='data'></td>
      <td class='data'></td> 
    </tr>
  </table>
</div>

<div class="background-gray"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>
  <title>Arsenal</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
  <%= Gon::Base.render_data %>
  <%= csrf_meta_tags %>
</head>


<body>
<nav class="navbar navbar-light bg-faded">
  <a class="navbar-brand" href="#">Arsenal</a>
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <%= link_to 'Player Info', player_index_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Game Info', fixture_index_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Statistics', statistic_index_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <%= link_to 'Graphics', graphic_index_path, class: 'nav-link' %>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
  <form class="form-inline navbar-form pull-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-info-outline" type="submit">Search</button>
  </form>
</nav>
<div class="container">

  <%= yield %>

</div>

</body>
</html>

app/views/player/_edit.html.erb
<%= bootstrap_form_for @player do |f| %>

  <div class="modal-body">
    <h2 class="text-center">Edit player information</h2>
    <%= f.text_field :name, :placeholder =>"Player name" %>
    <%= f.text_field :age, :placeholder =>"Age" %>
    <%= f.text_field :nationality, :placeholder =>"Nationality" %>
    <%= f.text_field :position, :placeholder =>"Position" %>
  </div>

  <div class="modal-footer">
    <%= f.submit "Submit", :class => "btn btn-info" %>
  </div>

<% end %>

app/views/player/index.html.erb
<div>
  <h1>Arsenal 2016-2017</h1>
  <img class="crest" src=<%= @team_data['crestUrl'] %> />
  <br />
</div>

<h5>Current Player Value:</h5>
<p><%= @market %> </p>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Nationality</th>
      <th>Position</th>
      <th>Market Value</th>
    </tr>
  </thead>
  <% @players.each do |player| %>
  <tr>
    <td> <%= link_to player.name, player_path(player) %></td>
    <td> <%= player.age %></td>
    <td> <%= player.nationality %></td>
    <td> <%= player.position %></td>
    <td> <%= player.marketValue %></td>
  </tr>
  <% end %>
</table>

<hr />

<%= bootstrap_form_for :player, :method => :post do |f| %>
    <%= f.text_field :name, :placeholder =>"Player name" %>
    <%= f.text_field :age, :placeholder =>"Age" %>
    <%= f.text_field :nationality, :placeholder =>"Nationality" %>
    <%= f.text_field :position, :placeholder =>"Position" %>
    <%= f.submit "Add a Player", class: "btn btn-default" %>
<% end %>

<hr />

app/views/player/show.html.erb
<h1><%= @player.name %></h1>

<img src=<%= @photo %>/>

<div>
  <%= link_to 'Return Home', player_index_path %>
</div>

<div>
<%= link_to "", edit_player_path(@player), :class => "fa fa-gears", :data => {toggle: 'modal', target: '#editModal' } %>
</div>

<div class="modal fade bs-modal-sm" id="editModal">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <%= render "edit" %>
    </div>
  </div>
</div>

app/views/statistic/index.html.erb
<h1>Stats</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Minutes Played</th>
      <th>Goals</th>
      <th>Assists</th>
      <th>Clean Sheets</th>
      <th>Goals Conceded</th>
      <th>Saves</th>
    </tr>
  </thead>

  <% @players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.position %></td>
      <td><%= player.minutes %></td>
      <td><%= player.goals %></td>
      <td><%= player.assists%></td>
      <td><%= player.clean_sheets %></td>
      <td><%= player.goals_conceded %></td>
      <td><%= player.saves %></td>
    </tr>
  <% end %>
</table>

<!-- <button class="see-data btn btn-info">See Some JSON!</button> -->

<div>
<select id="see-data" class="btn btn-default">
  <option value="">Choose a Statistic</option>
  <option value="goals">Goals</option>
  <option value="assists">Assists</option>
  <option value="minutes">Minutes Played</option>
</select>
</div>

<div id="graph"></div>

<hr />